id: PC20A6946
initial_creation_type: input
source_metadata:
  title: Topical Outlines
  language: de
  description: 'A series of topical or thematic outlines (sa bcad):'
  volume:
    56b3d2e9d5084cb4b75d013820b6b1fb:
      title: Synopsis of the Treasury of Abhidharma (Abhidharmakośa)
      parent: Abhidharma
    2f8d1fab4a584ce6b8cd327e08d6239a:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Aspiration Prayers
    30c1caaaab7545c3a8dd26f7dd1bf849:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Aspiration Prayers
    7669f4e02b96441ea99642e11e687bb4:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Confession
    4234291922724e38b27973800775a0c2:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Guru Rinpoche Prayers
    53a75adf176d4323b3db0ff47dbca843:
      title: Concise Explanatory Outline of the Heart of Wisdom
      parent: Prajñāpāramitā
    5d9fd6cfc10b4af1bb538b8a4a633d9c:
      title: Outline of the Ten Royal Sūtras
      parent: Sūtras
    bb6e5c2cdc3443db8503314f75b88ab0:
      title: An Outline of The Praise to Tārā with Twenty-One Verses of Homage
      parent: Tārā
created_at: '2022-03-01T06:23:56.643051'
last_modified_at: '2022-03-01T06:23:56.643054'
